### ISSUE TITLE
Archetype tutorial issues 

### ISSUE THREAD

**Issue by gwenchee** [cyclus/cyclus#1468] opened 2018-03-19 15:24 UTC
In the process of attempting the Cyclus archetype tutorial, two problems with the stubs generated from the Cycstub CLI have been found. In this issue, each problem is listed. @gyutaepark and I will work on fixing them. 

1) There is an error that occurs when trying to ``` python install.py ``` . This can be fixed by changing the Cmake file so that it will find Cyclus libraries. 

2) An error occurs when trying to run the example xml file. This is fixed by changing the archetype spec path to the path that leads to the ``` libarchetypetutorial.so ``` file where the term archetypetutorial is whatever you named the mylib when generating cycstub from the CLI.

**Comment by scopatz** [comment] 2018-03-19 17:19
Thanks for reporting!

**Comment by gyutaepark** [comment] 2018-03-21 17:22
Sorry for the delay and Thanks Gwen for making the issue.
I'll make a PR for this issue today.

**Comment by gyutaepark** [comment] 2018-04-03 22:11
#1470 has been merged. I believe the issue is now fixed. 
This issue will be closed.

**Closed by gyutaepark** 2018-04-03 22:11 UTC
